# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Server Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - '!*.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - '!*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create env file
      working-direcroty: ./server
        run: |
          echo "${{ secrets.SERVER_CREDENTIALS }}" > .env
    - name: Do clean install of node dependencies
      working-directory: ./server
      run: npm ci
    - name: Build server
      working-directory: ./server
      run: npm run build --if-present
    - name: Run server tests
      working-directory: ./server
      run: npm run test -- --passWithNoTests
